import React from 'react'

const About = () => {
    return (
        <div>
            <h3>About Page</h3>
            {/* <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam lectus felis, dapibus in suscipit et, aliquet at libero. Duis iaculis nec nibh id egestas. Praesent mi felis, vestibulum in elementum nec, accumsan eu turpis. Nam mauris ex, pellentesque ac porta ac, maximus ac urna. Etiam a interdum arcu. Aliquam tincidunt in justo non congue. Aliquam varius orci vel commodo rhoncus. Duis viverra quam eget risus egestas gravida pulvinar at leo. Proin sed efficitur libero. Pellentesque hendrerit ligula a eleifend viverra. Etiam ullamcorper ex fringilla varius cursus. Proin facilisis lacinia nisi, ultricies lacinia diam auctor quis.

                Proin maximus vel mauris id commodo. Praesent accumsan libero quis sem ornare ultrices. Sed aliquam iaculis ultrices. Etiam pulvinar tempus enim, sed posuere ex facilisis et. Sed sagittis nibh a velit iaculis aliquam. Aliquam in arcu elementum, dictum odio at, laoreet orci. Ut in pharetra risus. Suspendisse potenti. Quisque mattis, velit quis cursus fringilla, dui enim blandit magna, nec condimentum tellus lorem sit amet neque. Maecenas eget efficitur tellus. Nulla tincidunt, dui vitae tincidunt pellentesque, mi dui rhoncus neque, in malesuada tortor velit quis nulla. Quisque ac arcu in nulla rutrum placerat. Quisque viverra tempor pulvinar. Mauris sollicitudin vel diam in pellentesque. Morbi interdum semper velit, eu vehicula purus sollicitudin non.

                Fusce in sapien lacus. Proin tincidunt magna at mi blandit condimentum vitae nec quam. Duis nec scelerisque sem, ut blandit mi. Vestibulum dictum ipsum leo, in aliquam enim pulvinar et. Suspendisse aliquam consequat posuere. Nulla facilisi. Sed tincidunt elit libero, id rhoncus felis fringilla vel. Aliquam finibus suscipit nulla, eu fermentum est laoreet et. Quisque rutrum magna id ligula interdum congue. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nunc vitae justo dictum, ultricies mi sed, scelerisque justo. Vestibulum vel est suscipit, volutpat purus a, laoreet sapien.

                Aliquam a leo sollicitudin nibh rutrum dignissim a non nisl. Etiam placerat, nisi in placerat euismod, leo dolor eleifend odio, vel suscipit tellus risus venenatis neque. Curabitur massa felis, placerat eget tempus sit amet, bibendum ut eros. Mauris placerat ipsum mollis pharetra sagittis. Nulla eget metus interdum, varius lectus non, interdum neque. Sed lobortis blandit condimentum. Quisque venenatis in nisi eget mollis. Morbi sagittis metus pharetra bibendum tempor. Cras bibendum ornare lectus at cursus. Morbi dui neque, luctus vitae tellus id, commodo volutpat nibh. Ut ultricies libero diam, eu molestie felis tincidunt sed. Duis facilisis neque turpis, eget interdum arcu hendrerit imperdiet. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.

                Ut dictum arcu nec luctus bibendum. Pellentesque tempus felis vehicula erat sagittis venenatis. Nam consequat justo urna. Sed ac maximus ipsum. Nulla nec metus nec dolor mollis interdum. Vivamus ut sagittis enim. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed at felis risus. Integer risus lectus, interdum ut posuere sed, porta quis orci. Sed eget iaculis turpis, ac dignissim erat. Fusce ac condimentum nulla. Morbi in dolor in nunc pulvinar pretium.

                Fusce a fermentum diam, a sollicitudin diam. Integer vel porttitor enim, nec imperdiet ipsum. Etiam in justo in dolor faucibus ultrices id sed felis. Donec dictum maximus arcu, ut pretium diam pharetra sodales. Phasellus pellentesque nunc ac nibh congue, at fringilla nisl mattis. Donec luctus, ex sit amet lobortis ultrices, lectus purus tempor urna, in vehicula diam quam eget erat. Phasellus enim elit, ullamcorper id dolor ut, luctus mollis dolor. Nam pulvinar laoreet mi at vehicula. Donec ultricies cursus elit sit amet egestas. In molestie ante nisl, id molestie sem porttitor vitae. Proin imperdiet suscipit vehicula. Fusce eget mi arcu. Sed eget bibendum metus. Donec a elit at orci facilisis sagittis.

                Praesent mauris magna, vulputate at semper eget, eleifend eu orci. Mauris a sem in odio ullamcorper congue. Donec in erat odio. Sed eget auctor odio, sit amet finibus neque. In pharetra nisl ac libero semper, et cursus nunc molestie. Donec nec elit eu odio iaculis lobortis. Ut aliquet elit at semper fermentum. Donec bibendum tincidunt pharetra. Proin ultricies, turpis eu viverra blandit, nibh eros porta massa, ac convallis dolor ex in ligula. Nulla risus erat, finibus vitae sem id, dignissim consectetur nulla. Aliquam eget ultricies tortor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec at vestibulum libero. Donec laoreet sodales condimentum. Maecenas finibus non est id mollis.

                Vivamus mi purus, porttitor non tellus et, sagittis luctus est. Sed enim ex, dictum a accumsan a, fermentum in nibh. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam ultricies porta enim non euismod. Mauris consequat metus sit amet justo mollis euismod. Morbi ultrices nulla id tortor sodales, a sollicitudin tortor mattis. Duis vestibulum ex ac magna vestibulum laoreet eu ac magna. Aenean mollis felis vel ipsum fringilla porttitor. Vivamus suscipit, orci sit amet venenatis tincidunt, dolor neque cursus mi, eget convallis metus dolor sit amet enim. In efficitur quis dui in luctus. Sed vitae enim tristique, consectetur nibh et, maximus turpis. Vestibulum et laoreet diam. Donec posuere massa eget felis laoreet, ut imperdiet velit imperdiet. Donec condimentum turpis id orci ullamcorper, ac tincidunt ante convallis. Curabitur eu tristique ipsum, et sagittis magna.

                Ut imperdiet augue augue, id varius nulla tempor eget. Integer justo quam, egestas vitae turpis at, placerat cursus quam. Praesent aliquam porta dolor ac lacinia. Vivamus eu molestie dolor. Cras lorem est, ultricies non risus eget, malesuada semper eros. Nulla nec accumsan nisl, vitae ultrices felis. Ut varius lorem ac orci vulputate, ut cursus magna bibendum. Curabitur faucibus cursus nisi, non viverra lectus vestibulum at. Aliquam erat volutpat. Nunc semper placerat massa, nec gravida ante pellentesque vel. Quisque ultricies eu felis nec vulputate. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Duis eu sagittis enim, nec vehicula augue. Vivamus in maximus sem, ut euismod eros. Etiam ullamcorper sit amet risus nec euismod.

                Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed auctor justo ipsum, et aliquam elit interdum aliquam. Fusce ut porttitor leo. Donec finibus nulla id ipsum cursus facilisis. Donec sollicitudin hendrerit felis nec fringilla. Vestibulum a dolor vel ex varius commodo. Morbi arcu nisl, interdum et orci a, efficitur laoreet risus. Vivamus vitae nulla ipsum. Quisque commodo, lectus condimentum commodo suscipit, nibh lectus convallis diam, ac cursus justo velit in elit. Suspendisse potenti. Phasellus at nisl volutpat, tristique nibh quis, faucibus neque. Proin ultricies consectetur libero quis hendrerit. Proin vitae commodo libero, eu ullamcorper sapien. Vivamus pulvinar mi justo, vel dignissim eros hendrerit eu.

                Phasellus suscipit accumsan mauris a imperdiet. Nam in eros nec est pharetra imperdiet. Quisque tincidunt eleifend tempor. Sed et fermentum orci, ut ornare risus. Duis nec odio a lorem condimentum elementum sed vitae erat. Praesent bibendum massa non sapien aliquam, in imperdiet lacus eleifend. Praesent sed lobortis tortor, ut pellentesque lectus. Donec at viverra massa. Cras ullamcorper lacus purus, nec finibus magna iaculis in. Suspendisse egestas lacus arcu, dictum iaculis elit fringilla ut. Cras facilisis leo at felis tempor, eget volutpat est tincidunt. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce at tortor a elit dictum accumsan quis eget ex. Cras tempus efficitur cursus. Mauris fringilla nibh lacus, id mollis quam pulvinar ut. Mauris placerat lacus ac hendrerit mattis.

                In in sem iaculis, posuere nibh pellentesque, gravida massa. Vivamus diam turpis, rutrum laoreet massa eu, fermentum vehicula ex. Etiam rhoncus dolor et odio consequat, id malesuada ex tincidunt. Morbi quis orci vitae lacus congue pretium. Morbi vulputate varius venenatis. Duis id nunc aliquet, dignissim justo et, ultrices velit. Etiam at mauris luctus, bibendum tellus ut, egestas lacus. Proin posuere nec risus vel mattis. Fusce imperdiet tempus hendrerit. Nunc eu mauris volutpat, dapibus magna eu, porttitor erat. Fusce elit sem, interdum nec sem a, porta interdum sapien. Aliquam dictum, velit id laoreet dapibus, lorem turpis pretium risus, id porttitor nunc lectus sed metus. Donec semper eget libero ut elementum. Suspendisse ut metus iaculis mi fermentum bibendum.

                Fusce vestibulum tortor id elit tincidunt vulputate. Morbi euismod fermentum nibh id malesuada. Integer fringilla, orci ut vulputate egestas, magna urna vehicula nulla, sit amet vulputate libero libero at ipsum. Cras nulla justo, tristique eget rhoncus ut, porta quis risus. Nullam scelerisque consectetur arcu, nec euismod sem dignissim eu. Nunc malesuada arcu nec accumsan egestas. Donec finibus semper tempor. Quisque dictum, ante vel porttitor pellentesque, justo mauris vestibulum lectus, sed dapibus sapien velit ut nulla. Suspendisse eleifend sodales augue eu convallis. Vivamus sed cursus quam. Sed sagittis ante augue, vitae imperdiet lectus varius at. Fusce felis ipsum, vulputate nec urna vel, pretium congue erat.

                Aenean non lorem vitae nibh suscipit dapibus at in magna. Morbi vitae magna orci. Integer volutpat odio fringilla lorem ultricies, quis dignissim massa fringilla. Donec vehicula massa non sem suscipit pellentesque. Duis sit amet tempus erat, ac rutrum ante. Donec eu elementum tellus, et laoreet orci. Suspendisse cursus blandit dolor, eget suscipit nunc tincidunt sit amet. Cras at iaculis erat. Aliquam sed libero ultrices tellus pretium sodales vel sed magna. Nunc porttitor at augue id pellentesque. Duis ac purus vitae lacus cursus ornare. Morbi tempus nec tortor ac ultrices. Aliquam tincidunt nulla sit amet purus placerat, sed vulputate diam vestibulum. Suspendisse erat mi, lobortis ut dictum nec, sagittis eu magna. Donec eu congue neque. Etiam faucibus, leo at vulputate tempor, odio purus bibendum turpis, nec pulvinar tellus eros scelerisque nisi.

                Sed eu porttitor eros. Morbi faucibus, lorem at dignissim vestibulum, dui nisl placerat enim, nec eleifend metus nisi ut nisi. Proin eu sagittis metus, nec volutpat nulla. Duis a sapien est. Vestibulum vitae orci eget arcu vestibulum mattis eu tristique massa. Phasellus faucibus lobortis ante sed vulputate. Maecenas sollicitudin suscipit odio, ac consequat tortor pretium a. Donec quis tristique dui. Nullam eu nunc sed lacus pulvinar tincidunt vitae nec ante. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec hendrerit posuere ante eget pharetra. Morbi ut convallis velit. Morbi fringilla ipsum ut ipsum imperdiet placerat. Suspendisse at sollicitudin orci, vitae molestie ante.

                Integer lacinia non eros sit amet pulvinar. Cras ullamcorper neque nec enim cursus venenatis. Integer lacinia imperdiet facilisis. Nulla vitae est ac ex lacinia laoreet sed in massa. Nullam non faucibus nunc. Curabitur purus odio, dictum eu dapibus eget, laoreet vitae quam. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec diam neque, ultricies id dui non, molestie vehicula dolor. Aliquam facilisis aliquam elit, a porta nisi congue eleifend. Nunc odio dolor, condimentum non vestibulum ut, vulputate non augue. Sed vel tortor nunc. Donec urna arcu, euismod a leo ut, laoreet laoreet metus.

                Maecenas luctus porta ligula ut tincidunt. Mauris tincidunt sagittis sollicitudin. Morbi elementum lacinia malesuada. Aliquam pretium facilisis fringilla. Vestibulum nec malesuada magna, non molestie nisi. Curabitur tempor sem at eros commodo iaculis quis vitae velit. Nullam velit tellus, scelerisque sit amet laoreet et, semper a nunc.

                Integer enim velit, varius sed augue non, bibendum efficitur velit. Nulla molestie lorem rutrum felis finibus tincidunt eget elementum leo. Donec a fringilla quam, eget scelerisque ipsum. Sed efficitur, tortor tincidunt sollicitudin aliquam, nunc ante bibendum mauris, ut aliquet lorem metus ut eros. Curabitur tellus augue, vestibulum nec nisl vitae, placerat consequat velit. Proin sollicitudin mi nisi, sit amet hendrerit nisi vulputate et. Maecenas gravida est nisl, mattis luctus tortor tempus commodo. Mauris maximus, turpis in eleifend pharetra, mi tortor luctus neque, eu euismod lacus augue in velit. Pellentesque tincidunt ligula vitae nunc molestie vehicula. Cras tempus porta tellus, id hendrerit erat.

                Praesent vulputate, leo consectetur tempor lobortis, sem urna fringilla turpis, non mattis urna leo sit amet augue. Mauris a faucibus sem. Etiam eu ipsum non justo lacinia scelerisque. Cras pretium pretium semper. Cras convallis erat quis urna egestas, eu malesuada nisi tempus. Nunc fermentum diam eget sem condimentum bibendum. Nullam tincidunt, tortor sed vulputate convallis, turpis velit bibendum augue, ut lacinia elit ante ut lacus. Phasellus orci lorem, hendrerit et odio sed, mollis porttitor ante. Cras ex quam, feugiat nec enim id, pellentesque ullamcorper nisl. Quisque tempus volutpat tellus vitae consequat.

                Aenean malesuada nibh nec mi ultrices, non porta nulla facilisis. Donec sed egestas magna. Maecenas enim eros, blandit eget lorem sed, accumsan egestas mi. Ut ut faucibus massa. Maecenas sapien ex, rutrum vitae convallis vel, aliquam tempus sapien. Nam dapibus sem id mollis pretium. Maecenas scelerisque consequat metus vel iaculis. Donec eros lorem, ullamcorper vel nunc in, tempor vehicula erat. Nunc laoreet felis a bibendum finibus. Aenean fermentum feugiat est.

                Vestibulum id ultrices purus, ac tincidunt sapien. Sed velit dolor, tristique quis ligula eget, gravida gravida arcu. Donec ut enim in eros iaculis posuere auctor eu dui. Sed turpis turpis, bibendum eu dui in, luctus dignissim tellus. Cras ullamcorper sem eget tempor lobortis. Etiam velit massa, congue ac nisi id, dignissim imperdiet purus. In vestibulum et diam sit amet accumsan.

                Ut ultrices efficitur venenatis. Vivamus erat odio, semper ut risus eget, varius fringilla est. Morbi feugiat eu nunc non dignissim. Phasellus ac euismod urna. Cras ut dignissim odio. Praesent sit amet vehicula ipsum. In consectetur, magna et facilisis feugiat, sapien tortor dignissim ex, quis rhoncus arcu purus vel ante. Ut vel ante hendrerit, gravida mi in, malesuada magna. Cras elementum malesuada tellus, a vestibulum magna dapibus vitae. Vivamus accumsan turpis varius nunc sagittis, ut pharetra odio vestibulum. Maecenas ut ipsum tempus, sollicitudin nibh eget, lacinia massa. Nullam fringilla ligula at tellus vulputate, quis tincidunt ligula fermentum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas nec tincidunt nunc. Morbi mattis, mauris a gravida cursus, ligula magna tristique eros, vel posuere metus tortor sollicitudin felis. Curabitur lectus nisl, elementum sed arcu nec, consectetur posuere neque.

                Etiam bibendum sapien et sodales pharetra. Aenean eu lorem suscipit lectus hendrerit lacinia a vitae lectus. Aliquam quis porta sem. Sed lacinia urna mi, ac dictum ex luctus eu. Suspendisse vitae fringilla tellus, vitae commodo elit. Cras vel tempor nulla, sit amet lobortis libero. Curabitur scelerisque placerat neque non sagittis. Vestibulum eu augue ullamcorper, dignissim orci in, euismod est. Mauris sed orci semper, laoreet arcu ac, rutrum elit. Proin eget pretium erat. Nullam augue nisi, pellentesque at feugiat ut, tristique ac turpis. Aliquam finibus placerat finibus. Vivamus purus tortor, molestie eget est id, dictum rutrum enim. In mollis arcu quis risus rutrum ultrices. Fusce neque erat, vulputate vel accumsan convallis, tincidunt in tellus.

                Etiam pharetra neque nibh, et faucibus lectus tempor sit amet. Donec laoreet feugiat lorem, eu lobortis lacus pellentesque id. Nulla arcu elit, placerat at ullamcorper id, pulvinar ac nisl. Curabitur et sem mi. Nulla pellentesque metus vel velit hendrerit interdum. Proin at aliquet nibh. Phasellus consequat urna purus, a efficitur nulla fermentum nec. Vestibulum sit amet justo nulla. Pellentesque leo erat, tincidunt nec orci vitae, pulvinar congue augue. Sed auctor, lectus vitae elementum iaculis, erat justo pellentesque velit, at vulputate mauris odio consectetur urna. Morbi egestas dolor vel gravida faucibus. Cras ut tellus elementum, egestas urna ac, laoreet nibh. Nulla id quam elit. Donec eget fermentum ligula.

                Ut euismod non enim ut rutrum. Integer varius viverra vulputate. Curabitur ante ante, placerat quis faucibus ut, venenatis vitae ante. Nullam efficitur ligula quis nunc congue accumsan. Nullam vitae ullamcorper libero. Curabitur dignissim lacus felis, sit amet scelerisque arcu luctus id. Sed ut ligula vitae nibh vulputate semper. Phasellus eget mi pulvinar, rutrum leo a, luctus elit. Ut aliquam nisl id sodales iaculis. Aliquam ullamcorper sed erat ut efficitur. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In rutrum pellentesque pharetra.
            </p> */}
        </div>
    )
}
export default About